

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  #these labels are deployment related labels.
  labels:
    component: frontend
    project: expense
    tier: web
spec:
  replicas: 2
  selector:
    matchLabels:
      component: frontend
      project: expense
      tier: web
#below is pod definition
  template:
    metadata:
     labels:
       component: frontend
       project: expense
       tier: web
    spec:
       containers:
       - name: frontend
         image: joindevops/frontend:v1.0    ## lingadevops/frontend:v1.0
        #  resources:
        #    requests:
        #      cpu: "100m"
        #      memory: "256Mi"
        #    limits:
        #      cpu: "150m"
        #      memory: "256Mi"
        #  volumeMounts:
        #  - name: nginx-conf
        #    mountPath: /etc/nginx/nginx.conf
        #    subPath: nginx.conf
        #    readOnly: true
         # envFrom:
         #- configMapRef
         #  name: frontend
      volumes:
      - name: nginx-conf
        configMap:
          name: frontnd
          items:
          - key: nginx.conf
            path: nginx.conf
   

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: expense
spec:
  type: LoadBalancer
  selector:
      component: frontend
      project: expense
      tier: web
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port
        
---
# apiVersion: elbv2.k8s.aws/v1beta1
# kind: TargetGroupBinding
# metadata:
#   name: frontend
#   namespace: expense
# spec:
#   serviceRef:
#     name: frontend # rroute traffic to the awesome-service
#     port: 80
#   targetGroupARN: rn:aws:elasticloadbalancing:us-east-1:315069654700:targetgroup/expense-dev-frontend/709ac65514f95b53












           