apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql # mysql component service name
  #DB_HOST:db-dev.lingaiah.online

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  #these labels are deployment related labels.
  labels:
    component: backend
    project: expense
    tier: app
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: app
#below is pod definition
  template:
    metadata:
     labels:
       component: backend
       project: expense
       tier: app
    spec:
       initContainers:
       - name: init-myservice
         image: busybox:1.28
         command: ['sh', '-c',"until nslookup db-dev.lingaiah.online; do echo waiting for myservice; sleep 2; done"]
       containers:
       - name: backend
         image: joindevops/backend:v1.0 ##lingadevops/backend:v1.0
         envFrom:
         - configMapRef:
           name: backend
        #  resources:
        #    requests:
        #      cpu: "100m"
        #      memory: "256Mi"
        #  livenessProbe:
        #    httpGet:
        #      path: /health
        #      port: 8080
        #      failureThreshould: 2
        #      periodSeconds: 5
        #      initialDelaySeconds: 30
        #  readinessProbe:
        #    httpGet:
        #      path: /health
        #      port: 8080
        #      failureThreshould: 2
        #      periodSeconds: 5
        #      initialDelaySeconds: 30


---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
      component: backend
      project: expense
      tier: app
  ports:
  - protocol: TCP
    port: 3306 #service-port
    targetPort: 3306 #target-port
           